name    = "TestProject"
version = "0.1.0"

[deps]
Core = ""

    [deps.dev]
    json        = ">= 2.3"
    readline    = "== 0.4.2"
    jquyery     = "<= 12.2.0 && > 13.0"
    rubycopy    = "~> 1.2.2"
    noconstrait = ""

    [deps.prod]
    pq = ""